--- #YAML:1.0
name: Posy-Plugin-TextToHTML
version: 0.61
author:
  - Kathryn Andersen
abstract: Posy plugin to convert plain text files to HTML.
license: perl
requires:
  HTML::TextToHTML: 2.33
  Posy: 0.9
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::TextToHTML:
    file: lib/Posy/Plugin/TextToHTML.pm
    version: 0.61
generated_by: Module::Build version 0.2607
